__version__ = '0.1'
__title__ = 'hippiepug'
__author__ = 'Bogdan Kulynych'
__email__ = 'hello@bogdankulynych.me'
__copyright__ = 'Copyright (c) 2018 Bogdan Kulynych, EPFL SPRING Lab'
__description__ = 'Sublinear-traversal blockchains and efficient key-value Merkle trees with a flexible storage backend'
__license__ = 'AGPLv3'
